# Generated by Django 4.2.6 on 2023-12-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwd',
            name='user',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
